# Generated by Django 3.0.3 on 2020-03-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pemail', models.CharField(max_length=100)),
                ('pphone', models.CharField(max_length=100)),
                ('paddress', models.TextField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pemail', models.CharField(max_length=100)),
                ('pphone', models.CharField(max_length=100)),
                ('paddress', models.TextField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occupational_hazard', models.IntegerField()),
                ('Genetic_Risk', models.IntegerField()),
                ('chronic_lung_cancer', models.IntegerField()),
                ('smocking', models.IntegerField()),
                ('passive_smoker', models.IntegerField()),
                ('chest_pain', models.IntegerField()),
                ('coughing_of_blood', models.IntegerField()),
                ('fatigue', models.IntegerField()),
                ('weight_loss', models.IntegerField()),
                ('dry_cough', models.IntegerField()),
                ('clubbing_of_finger_nail', models.IntegerField()),
            ],
        ),
    ]
