# Generated by Django 3.0.3 on 2020-03-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='copd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientemail', models.CharField(max_length=100)),
                ('docname', models.CharField(max_length=100)),
                ('reportof', models.CharField(max_length=100)),
                ('reportnm', models.CharField(max_length=100)),
                ('lipcolor', models.CharField(max_length=100)),
                ('FEV', models.CharField(max_length=100)),
                ('Smkintensity', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=100)),
                ('riskvalue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='diabetesreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientemail', models.CharField(max_length=100)),
                ('docname', models.CharField(max_length=100)),
                ('reportof', models.CharField(max_length=100)),
                ('reportnm', models.CharField(max_length=100)),
                ('glucose', models.CharField(max_length=100)),
                ('bloodpressure', models.CharField(max_length=100)),
                ('insulin', models.CharField(max_length=100)),
                ('bmi', models.CharField(max_length=100)),
                ('diapedgree', models.CharField(max_length=100)),
                ('riskvalue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Heartreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientemail', models.CharField(max_length=100)),
                ('docname', models.CharField(max_length=100)),
                ('reportof', models.CharField(max_length=100)),
                ('reportnm', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=100)),
                ('trestbps', models.CharField(max_length=100)),
                ('chol', models.CharField(max_length=100)),
                ('fbs', models.CharField(max_length=100)),
                ('exang', models.CharField(max_length=100)),
                ('ca', models.CharField(max_length=100)),
                ('riskvalue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lungreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientemail', models.CharField(max_length=100)),
                ('docname', models.CharField(max_length=100)),
                ('reportof', models.CharField(max_length=100)),
                ('reportnm', models.CharField(max_length=100)),
                ('Genetic_Risk', models.CharField(max_length=100)),
                ('Occupational_hazard', models.CharField(max_length=100)),
                ('chest_pain', models.CharField(max_length=100)),
                ('chronic_lung_cancer', models.CharField(max_length=100)),
                ('clubbing_of_finger_nail', models.CharField(max_length=100)),
                ('coughing_of_blood', models.CharField(max_length=100)),
                ('dry_cough', models.CharField(max_length=100)),
                ('fatigue', models.CharField(max_length=100)),
                ('passive_smoker', models.CharField(max_length=100)),
                ('smocking', models.CharField(max_length=100)),
                ('weight_loss', models.CharField(max_length=100)),
                ('riskvalue', models.CharField(max_length=100)),
            ],
        ),
    ]
