# Generated by Django 2.1.1 on 2020-05-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_copd_diabetesreport_heartreport_lungreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='BipolarReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientemail', models.CharField(max_length=100)),
                ('docname', models.CharField(max_length=100)),
                ('reportof', models.CharField(max_length=100)),
                ('reportnm', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Right_answers', models.CharField(max_length=100)),
                ('Audio_prosody', models.CharField(max_length=100)),
                ('Combined_channel', models.CharField(max_length=100)),
                ('Face_video', models.CharField(max_length=100)),
                ('Body_video', models.CharField(max_length=100)),
                ('Positive_valence', models.CharField(max_length=100)),
                ('Negative_valence', models.CharField(max_length=100)),
                ('Dominant', models.CharField(max_length=100)),
                ('Submissive', models.CharField(max_length=100)),
            ],
        ),
    ]
